<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class LoginRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'id' => 'required|email|max:64|min:6',
            'password' => 'required'
        ];
    }

    /**
     * TODO: Change the autogenerated stub
     *
     * @return array|string[]
     */
    public function messages()
    {
        return [
            'id.required' => 'Email không được trống cưng ơi',
            'password.required' => 'password không được trống cưng ơi',

            'id.email' => 'Email phải là Email cưng ơi',
            'id.max' => 'Email dài quá cưng ơi',
            'id.min' => 'Email ngắn quá cưng ơi',
        ];
    }
}
