<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class LoginRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|email|min:6|max:64',
            'password' => 'required',
        ];
    }

    /**
     * Change the autogenerated stub
     *
     * @return array|string[]
     */
    public function messages()
    {
        return [
            'email.required' => 'Email không được trống',
            'email.email' => 'Email phải là một địa chỉ email',
            'email.min' => 'Email quá ngắn',
            'email.max' => 'Email quá dài',

            'password.required' => 'Password không được trống',
        ];
    }
}
